### ISSUE TITLE
Hangs when called to capture output

### ISSUE THREAD

**Issue by NCN** [pstadler/non-terminating-bash-processes#1]
Thanks for this, it's exactly what I needed. However if I try to capture the output into a new shell variable, like so:
`variable=`discover-vnc.sh``

It hangs forever. I think it's related to this: http://stackoverflow.com/questions/13782039/shell-script-hangs-but-only-when-called-into-a-variable-or-strace

But I cannot figure out a solution.
Thanks.

**Comment by pstadler** [comment]
Try this: `foo=$(./discover-vnc.sh 2>/dev/null); echo $foo;`

**Comment by pstadler** [comment]
On a side note, if 0.5 seconds until kill is to little time for you, simply increase the value here: https://github.com/pstadler/non-terminating-bash-processes/blob/master/discover-vnc.sh#L25

**Comment by NCN** [comment]
Thank you, I did increase the 0.5 to 2.5 which fixed a problem where I wasn't getting all my devices sometimes.

Incidentally your suggestion didn't work form me. However I decided to proceed by directing the output to a tmp file and reading it back in, which while hacky will work ok for my application.

**Comment by pstadler** [comment]
You probably should integrate the discovery logic within your actual script. Interestingly, the above command works for me using zsh and bash.
