### ISSUE TITLE
Child process termination kills terminal session

### ISSUE THREAD

**Issue by jaygooby** [pstadler/non-terminating-bash-processes#2]
Thanks for this script, it's got some nice bash tricks in it, but there's a problem with the child process termination.

The script runs fine when invoked as `./discover-vnc.sh`, but if you attempt to use it as part of a further script, e.g. 

```
for vnc in $(./discover-vnc.sh); do echo "Found $vnc"; done
```

The child termination kills my current terminal session (I'm on OS X 10.10.5, GNU bash, version 3.2.57). I presume this is due to the assumption that `discover-vnc.sh` is the primary process and will not be used elsewhere in other scripts.

Rather than killing at the end of `discover-vnc.sh`, you could simply look for the non-terminated `dns-sd` process with e.g. `pgrep`

```
# kill child processes
# kill -13 0 # causes problems with subshells
kill -13 $(pgrep dns-sd)
```

**Comment by pstadler** [comment]
Indeed, that's a good idea I guess. However, I don't know how to apply this to the docs. Care for opening a PR mentioning this in the readme? :)

**Comment by jaygooby** [comment]
I sent you a PR https://github.com/pstadler/non-terminating-bash-processes/pull/3

**Comment by pstadler** [comment]
Thanks!
